"""
equipment blueprint
"""
from datetime import datetime, timedelta
from flask import (Blueprint, render_template, request, redirect, url_for, flash,
                   jsonify, send_file, session, g, current_app)
from flask_login import login_required, current_user
from flask_babel import gettext as _
from werkzeug.utils import secure_filename
import os, io, json

from models import (db, EquipmentMaintenance, EquipmentPart, EquipmentComponent,
                    EquipmentPartOrder, EquipmentMROPhoto, Machine, VoorraadItem,
                    VoorraadMutatie)
from utils import ensure_fpdf, find_pdf_font, log_audit, log_system, role_required, safe_commit, safe_date, safe_float, safe_int, sanitize_like

bp = Blueprint('equipment', __name__)

def gen_eq_number():
    today = datetime.utcnow()
    prefix = today.strftime('%Y%m%d')
    last = EquipmentMaintenance.query.filter(EquipmentMaintenance.number.like(f'EQ-{prefix}-%')).order_by(EquipmentMaintenance.id.desc()).first()
    num = int(last.number.split('-')[2]) + 1 if last else 1
    return f'EQ-{prefix}-{num:04d}'


def gen_eq_order_number():
    today = datetime.utcnow()
    prefix = today.strftime('%Y%m%d')
    last = EquipmentPartOrder.query.filter(EquipmentPartOrder.order_number.like(f'EPO-{prefix}-%')).order_by(EquipmentPartOrder.id.desc()).first()
    num = int(last.order_number.split('-')[2]) + 1 if last else 1
    return f'EPO-{prefix}-{num:04d}'


@bp.route('/equipment')
@login_required
@role_required('admin', 'director', 'technician')
def equipment_list():
    q = EquipmentMaintenance.query
    serial = request.args.get('serial', '').strip()
    if serial:
        q = q.filter(EquipmentMaintenance.serial.ilike(f'%{sanitize_like(serial)}%'))
    page = request.args.get('page', 1, type=int)
    pagination = q.order_by(EquipmentMaintenance.date.desc()).paginate(page=page, per_page=25, error_out=False)
    records = pagination.items
    orders = EquipmentPartOrder.query.order_by(EquipmentPartOrder.created_at.desc()).limit(20).all()
    machines = Machine.query.order_by(Machine.name).all()
    # Find warehouse items linked to mule maintenance parts that are low or out of stock
    used_wh_ids = db.session.query(EquipmentPart.warehouse_item_id).filter(
        EquipmentPart.warehouse_item_id.isnot(None)).distinct().all()
    used_wh_ids = [w[0] for w in used_wh_ids]
    low_stock_parts = VoorraadItem.query.filter(
        VoorraadItem.id.in_(used_wh_ids),
        VoorraadItem.hoeveelheid <= VoorraadItem.minimum
    ).order_by(VoorraadItem.naam).all() if used_wh_ids else []
    return render_template('equipment.html', pagination=pagination, records=records, orders=orders, machines=machines, serial=serial, low_stock_parts=low_stock_parts)


@bp.route('/equipment/report')
@login_required
@role_required('admin', 'director', 'technician')
def equipment_report():
    """Печатный отчёт по записям MRO (все или выбранные ?ids=1,2,3)."""
    records = _equipment_ids_query(request.args.get('ids', '')).order_by(
        EquipmentMaintenance.date.desc(), EquipmentMaintenance.id.desc()).all()
    return render_template('equipment_report.html', records=records,
                           generated_at=datetime.now())


@bp.route('/equipment/export/pdf')
@login_required
@role_required('admin', 'director', 'technician')
def equipment_export_pdf():
    """PDF-экспорт записей MRO (все или выбранные ?ids=1,2,3)."""
    records = _equipment_ids_query(request.args.get('ids', '')).order_by(
        EquipmentMaintenance.date.desc(), EquipmentMaintenance.id.desc()).all()
    try:
        fpdf_mod = ensure_fpdf()
        FPDF = fpdf_mod.FPDF
    except Exception as e:
        import sys as _sys
        msg = f'{e} | python={_sys.executable} | path0={(_sys.path[0] if _sys.path else "")}'
        print(f'equipment_export_pdf: fpdf unavailable: {msg}')
        log_system('error', 'export', f'PDF export failed: fpdf unavailable: {msg}')
        flash(_('PDF export is temporarily unavailable') + f' — {e}', 'error')
        return redirect(url_for('equipment.equipment_list'))
    date_str = datetime.now().strftime('%d-%m-%Y %H:%M')
    title = _('Mule Maintenance Report')
    footer_txt = _('Generated by ProMaster CRM')
    page_txt = _('page')

    font_path = find_pdf_font()
    font_ok = {'unicode': bool(font_path)}
    print(f'equipment_export_pdf: font={font_path!r} records={len(records)}')

    def pdf_text(s):
        s = str(s if s is not None else '')
        if font_ok['unicode']:
            return s
        return s.encode('latin-1', 'replace').decode('latin-1')

    # Probe TTF embedding — stub fontTools cannot add_font
    if font_ok['unicode']:
        try:
            _probe = FPDF()
            _probe.add_font('AppFont', '', font_path)
        except Exception as _font_err:
            print(f'MRO PDF: add_font failed ({_font_err}), fallback Helvetica')
            font_ok['unicode'] = False

    try:
        return _build_mro_pdf(records, FPDF, font_ok['unicode'], font_path, pdf_text,
                              title, date_str, footer_txt, page_txt)
    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        print(f'equipment_export_pdf FAILED: {e}\n{tb}')
        log_system('error', 'export', f'MRO PDF export failed: {e}')
        flash(_('PDF export failed: %(err)s', err=str(e)), 'error')
        return redirect(url_for('equipment.equipment_list'))


def _build_mro_pdf(records, FPDF, unicode_font, font_path, pdf_text,
                   title, date_str, footer_txt, page_txt):
    class MroPDF(FPDF):
        def header(self):
            fn = 'AppFont' if unicode_font else 'Helvetica'
            self.set_font(fn, 'B', 12)
            self.cell(0, 8, pdf_text(f'{title} - ProMaster'), new_x='LMARGIN', new_y='NEXT')
            self.set_font(fn, '', 8)
            self.cell(0, 5, pdf_text(f'{date_str} - {len(records)} {_("records")}'),
                      new_x='LMARGIN', new_y='NEXT')
            self.ln(2)

        def footer(self):
            fn = 'AppFont' if unicode_font else 'Helvetica'
            self.set_y(-12)
            self.set_font(fn, '', 7)
            self.set_text_color(128)
            self.cell(0, 8, pdf_text(f'{footer_txt} - {page_txt} {self.page_no()}/{{nb}}'), align='C')

    pdf = MroPDF(orientation='P', unit='mm', format='A4')
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)
    if unicode_font:
        try:
            pdf.add_font('AppFont', '', font_path)
            pdf.add_font('AppFont', 'B', font_path)
            base_font = 'AppFont'
        except Exception:
            unicode_font = False
            base_font = 'Helvetica'
    else:
        base_font = 'Helvetica'
    pdf.add_page()

    def field_row(label, value, bold=False):
        if not value:
            return
        fn = 'AppFont' if unicode_font else 'Helvetica'
        pdf.set_font(fn, 'B' if bold else '', 9)
        pdf.cell(45, 6, pdf_text(label), border=0)
        pdf.set_font(fn, '', 9)
        pdf.multi_cell(0, 6, pdf_text(value), new_x='LMARGIN', new_y='NEXT')

    for idx, r in enumerate(records):
        if idx > 0:
            pdf.ln(4)
            if pdf.get_y() > 240:
                pdf.add_page()
        fn = 'AppFont' if unicode_font else 'Helvetica'
        # Заголовок записи
        pdf.set_fill_color(44, 62, 80)
        pdf.set_text_color(255)
        pdf.set_font(fn, 'B', 11)
        pdf.cell(0, 9, pdf_text(f'{r.number}  ·  {r.name}'), fill=True,
                 new_x='LMARGIN', new_y='NEXT')
        pdf.set_text_color(51)
        pdf.ln(2)

        field_row(_('Date'), r.date.strftime('%d.%m.%Y') if r.date else '')
        field_row(_('Serial'), r.serial)
        field_row(_('Machine'), r.machine.name if r.machine else '')
        field_row(_('Reason'), r.reason)
        field_row(_('Next Maintenance Date'), r.next_date.strftime('%d.%m.%Y') if r.next_date else '')
        field_row(_('Periodicity'), r.periodicity)
        field_row(_('Status'), r.status)
        field_row(_('Notes'), r.notes)
        if r.creator:
            field_row(_('Created by'), r.creator.display_name or r.creator.username)

        if r.parts:
            pdf.ln(1)
            pdf.set_font(fn, 'B', 9)
            pdf.cell(0, 6, pdf_text(_('Used Parts')), new_x='LMARGIN', new_y='NEXT')
            pdf.set_font(fn, 'B', 8)
            pdf.set_fill_color(236, 240, 241)
            pdf.cell(80, 6, pdf_text(_('Part')), border=1, fill=True)
            pdf.cell(35, 6, pdf_text('SPN'), border=1, fill=True)
            pdf.cell(25, 6, pdf_text(_('Qty')), border=1, fill=True)
            pdf.ln()
            pdf.set_font(fn, '', 8)
            for p in r.parts:
                pdf.cell(80, 6, pdf_text(p.name), border=1)
                pdf.cell(35, 6, pdf_text(p.number or ''), border=1)
                pdf.cell(25, 6, pdf_text(p.quantity), border=1)
                pdf.ln()

        if r.components:
            pdf.ln(1)
            pdf.set_font(fn, 'B', 9)
            pdf.cell(0, 6, pdf_text(_('Components')), new_x='LMARGIN', new_y='NEXT')
            pdf.set_font(fn, 'B', 8)
            pdf.set_fill_color(236, 240, 241)
            pdf.cell(40, 6, pdf_text(_('Type')), border=1, fill=True)
            pdf.cell(45, 6, pdf_text(_('Model')), border=1, fill=True)
            pdf.cell(30, 6, pdf_text(_('Size (mm)')), border=1, fill=True)
            pdf.cell(30, 6, pdf_text(_('Length')), border=1, fill=True)
            pdf.cell(20, 6, pdf_text(_('Qty')), border=1, fill=True)
            pdf.ln()
            pdf.set_font(fn, '', 8)
            for c in r.components:
                pdf.cell(40, 6, pdf_text(c.component_type or ''), border=1)
                pdf.cell(45, 6, pdf_text(c.model or ''), border=1)
                pdf.cell(30, 6, pdf_text(c.size or ''), border=1)
                pdf.cell(30, 6, pdf_text(c.length or ''), border=1)
                pdf.cell(20, 6, pdf_text(c.quantity), border=1)
                pdf.ln()

        if r.photos:
            pdf.ln(1)
            pdf.set_font(fn, 'B', 9)
            pdf.cell(0, 6, pdf_text(f'{_("Photos")} ({len(r.photos)})'),
                     new_x='LMARGIN', new_y='NEXT')
            y0 = pdf.get_y()
            x0 = pdf.l_margin
            for i, ph in enumerate(r.photos):
                if i > 0 and i % 4 == 0:
                    y0 += 32
                    x0 = pdf.l_margin
                    if y0 > 250:
                        pdf.add_page()
                        y0 = pdf.get_y()
                img_path = os.path.join(current_app.config['UPLOAD_FOLDER'], ph.filename)
                try:
                    pdf.image(img_path, x=x0 + (i % 4) * 40, y=y0, w=36, h=28)
                except Exception:
                    pass
            pdf.set_y(y0 + 32)

        # Подпись
        pdf.ln(6)
        pdf.set_font(fn, '', 8)
        pdf.set_text_color(120)
        pdf.cell(90, 8, pdf_text(f'{_("Performed by")}: ______________________'), border=0)
        pdf.cell(0, 8, pdf_text(f'{_("Signature")}: ______________________'), border=0)
        pdf.set_text_color(51)
        pdf.ln(10)

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return send_file(buf, mimetype='application/pdf',
                     download_name=f'mro_report_{datetime.now().strftime("%Y%m%d")}.pdf',
                     as_attachment=True)


def _equipment_ids_query(ids_param):
    """EquipmentMaintenance query filtered by comma-separated ids; empty = all."""
    q = EquipmentMaintenance.query
    if ids_param.strip():
        id_list = [safe_int(x) for x in ids_param.split(',') if x.strip()]
        if id_list:
            q = q.filter(EquipmentMaintenance.id.in_(id_list))
        else:
            q = q.filter(EquipmentMaintenance.id == -1)
    return q


@bp.route('/equipment/<int:eq_id>')
@login_required
@role_required('admin', 'director', 'technician')
def equipment_detail(eq_id):
    eq = EquipmentMaintenance.query.get_or_404(eq_id)
    return render_template('equipment_detail.html', eq=eq)


@bp.route('/equipment/new', methods=['GET', 'POST'])
@login_required
@role_required('admin', 'technician')
def equipment_new():
    if request.method == 'POST':
        try:
            date = datetime.strptime(request.form['date'], '%Y-%m-%d').date()
        except (ValueError, KeyError):
            flash(_('Invalid date format'), 'error')
            return redirect(url_for('equipment.equipment_new'))
        eq = EquipmentMaintenance(
            number=gen_eq_number(),
            name=request.form['name'],
            serial=request.form.get('serial', ''),
            machine_id=safe_int(request.form.get('machine_id')) or None,
            date=date,
            reason=request.form['reason'],
            next_date=(d := safe_date(request.form.get('next_date'))) and d.date() or None,
            periodicity=request.form.get('periodicity', ''),
            notes=request.form.get('notes', ''),
            created_by=current_user.id
        )
        db.session.add(eq)
        db.session.flush()
        # Add parts + deduct from warehouse
        wh_ids = request.form.getlist('part_warehouse_id')
        for i, pname in enumerate(request.form.getlist('part_name')):
            if pname.strip():
                wh_id = safe_int(wh_ids[i]) if i < len(wh_ids) and wh_ids[i] else None
                qty = safe_float(request.form.getlist('part_qty')[i], 1) if i < len(request.form.getlist('part_qty')) and request.form.getlist('part_qty')[i] else 1
                db.session.add(EquipmentPart(
                    equipment_id=eq.id,
                    warehouse_item_id=wh_id,
                    name=pname.strip(),
                    number=request.form.getlist('part_number')[i] if i < len(request.form.getlist('part_number')) else '',
                    quantity=qty
                ))
                # Deduct from warehouse
                if wh_id:
                    wi = VoorraadItem.query.get(wh_id)
                    if wi:
                        wi.hoeveelheid -= qty
                        db.session.add(VoorraadMutatie(
                            item_id=wh_id, type='uitgaand', hoeveelheid=qty,
                            opmerking=f'Mule Maintenance {eq.number}: {pname.strip()}',
                            user_id=current_user.id
                        ))
        # Add components
        comp_types = request.form.getlist('comp_type')
        comp_models = request.form.getlist('comp_model')
        comp_sizes = request.form.getlist('comp_size')
        comp_lengths = request.form.getlist('comp_length')
        comp_qtys = request.form.getlist('comp_qty')
        for i, ctype in enumerate(comp_types):
            if ctype:
                db.session.add(EquipmentComponent(
                    equipment_id=eq.id,
                    component_type=ctype,
                    model=comp_models[i] if i < len(comp_models) else '',
                    size=comp_sizes[i] if i < len(comp_sizes) else '',
                    length=comp_lengths[i] if i < len(comp_lengths) else '',
                    quantity=float(comp_qtys[i]) if i < len(comp_qtys) and comp_qtys[i] else 1
                ))
        # Add photos
        for photo in request.files.getlist('photos'):
            if photo and photo.filename:
                fn = secure_filename(f"mro_{eq.id}_{photo.filename}")
                photo.save(os.path.join(current_app.config['UPLOAD_FOLDER'], fn))
                db.session.add(EquipmentMROPhoto(equipment_id=eq.id, filename=fn))
        if not safe_commit():
            flash(_('Save failed'), 'error')
            return redirect(url_for('equipment.equipment_list'))
        log_audit('create', 'equipment', eq.id, f'{eq.number} — {eq.name}')
        flash(_('Equipment maintenance recorded'), 'success')
        return redirect(url_for('equipment.equipment_list'))
    machines = Machine.query.order_by(Machine.name).all()
    warehouse_items = VoorraadItem.query.order_by(VoorraadItem.naam).all()
    return render_template('equipment_form.html', eq=None, machines=machines, warehouse_items=warehouse_items)


@bp.route('/equipment/<int:eq_id>/edit', methods=['GET', 'POST'])
@login_required
@role_required('admin', 'technician')
def equipment_edit(eq_id):
    eq = EquipmentMaintenance.query.get_or_404(eq_id)
    if request.method == 'POST':
        try:
            eq.date = datetime.strptime(request.form['date'], '%Y-%m-%d').date()
        except (ValueError, KeyError):
            flash(_('Invalid date format'), 'error')
            return redirect(url_for('equipment.equipment_edit', eq_id=eq.id))
        eq.name = request.form['name']
        eq.serial = request.form.get('serial', '')
        eq.machine_id = safe_int(request.form.get('machine_id')) or None
        eq.reason = request.form['reason']
        eq.next_date = (d := safe_date(request.form.get('next_date'))) and d.date() or None
        eq.periodicity = request.form.get('periodicity', '')
        eq.notes = request.form.get('notes', '')
        EquipmentPart.query.filter_by(equipment_id=eq.id).delete()
        wh_ids = request.form.getlist('part_warehouse_id')
        for i, pname in enumerate(request.form.getlist('part_name')):
            if pname.strip():
                wh_id = safe_int(wh_ids[i]) if i < len(wh_ids) and wh_ids[i] else None
                qty = safe_float(request.form.getlist('part_qty')[i], 1) if i < len(request.form.getlist('part_qty')) and request.form.getlist('part_qty')[i] else 1
                db.session.add(EquipmentPart(
                    equipment_id=eq.id,
                    warehouse_item_id=wh_id,
                    name=pname.strip(),
                    number=request.form.getlist('part_number')[i] if i < len(request.form.getlist('part_number')) else '',
                    quantity=qty
                ))
                if wh_id:
                    wi = VoorraadItem.query.get(wh_id)
                    if wi:
                        wi.hoeveelheid -= qty
                        db.session.add(VoorraadMutatie(
                            item_id=wh_id, type='uitgaand', hoeveelheid=qty,
                            opmerking=f'Mule Maintenance {eq.number}: {pname.strip()}',
                            user_id=current_user.id
                        ))
        # Update components
        EquipmentComponent.query.filter_by(equipment_id=eq.id).delete()
        comp_types = request.form.getlist('comp_type')
        comp_models = request.form.getlist('comp_model')
        comp_sizes = request.form.getlist('comp_size')
        comp_lengths = request.form.getlist('comp_length')
        comp_qtys = request.form.getlist('comp_qty')
        for i, ctype in enumerate(comp_types):
            if ctype:
                db.session.add(EquipmentComponent(
                    equipment_id=eq.id,
                    component_type=ctype,
                    model=comp_models[i] if i < len(comp_models) else '',
                    size=comp_sizes[i] if i < len(comp_sizes) else '',
                    length=comp_lengths[i] if i < len(comp_lengths) else '',
                    quantity=float(comp_qtys[i]) if i < len(comp_qtys) and comp_qtys[i] else 1
                ))
        # Add new photos (existing ones are kept)
        for photo in request.files.getlist('photos'):
            if photo and photo.filename:
                fn = secure_filename(f"mro_{eq.id}_{photo.filename}")
                photo.save(os.path.join(current_app.config['UPLOAD_FOLDER'], fn))
                db.session.add(EquipmentMROPhoto(equipment_id=eq.id, filename=fn))
        if not safe_commit():
            flash(_('Save failed'), 'error')
            return redirect(url_for('equipment.equipment_list'))
        flash(_('Equipment maintenance updated'), 'success')
        return redirect(url_for('equipment.equipment_list'))
    machines = Machine.query.order_by(Machine.name).all()
    warehouse_items = VoorraadItem.query.order_by(VoorraadItem.naam).all()
    return render_template('equipment_form.html', eq=eq, machines=machines, warehouse_items=warehouse_items)


@bp.route('/equipment/<int:eq_id>/delete', methods=['POST'])
@login_required
@role_required('admin')
def equipment_delete(eq_id):
    eq = EquipmentMaintenance.query.get_or_404(eq_id)
    db.session.delete(eq)
    if not safe_commit():
        flash(_('Save failed'), 'error')
        return redirect(url_for('equipment.equipment_list'))
    flash(_('Equipment maintenance deleted'), 'success')
    return redirect(url_for('equipment.equipment_list'))


@bp.route('/equipment/photo/<int:photo_id>/delete', methods=['POST'])
@login_required
@role_required('admin', 'technician')
def equipment_photo_delete(photo_id):
    photo = EquipmentMROPhoto.query.get_or_404(photo_id)
    eq_id = photo.equipment_id
    try:
        os.remove(os.path.join(current_app.config['UPLOAD_FOLDER'], photo.filename))
    except OSError:
        pass
    db.session.delete(photo)
    if not safe_commit():
        flash(_('Save failed'), 'error')
    else:
        flash(_('Photo deleted'), 'success')
    return redirect(url_for('equipment.equipment_edit', eq_id=eq_id))


@bp.route('/equipment/order', methods=['POST'])
@login_required
@role_required('admin', 'technician')
def equipment_order():
    o = EquipmentPartOrder(
        order_number=gen_eq_order_number(),
        equipment_name=request.form.get('equipment_name', ''),
        part_name=request.form['part_name'],
        part_number=request.form.get('part_number', ''),
        quantity=safe_float(request.form.get('quantity'), 1),
        supplier=request.form.get('supplier', ''),
        urgency=request.form.get('urgency', 'normal'),
        notes=request.form.get('notes', ''),
        created_by=current_user.id
    )
    db.session.add(o)
    if not safe_commit():
        flash(_('Save failed'), 'error')
        return redirect(url_for('equipment.equipment_list'))
    flash(_('Part order created'), 'success')
    return redirect(url_for('equipment.equipment_list'))


@bp.route('/equipment/order/<int:order_id>/status', methods=['POST'])
@login_required
@role_required('admin', 'technician')
def equipment_order_status(order_id):
    o = EquipmentPartOrder.query.get_or_404(order_id)
    new_status = request.form.get('status')
    if new_status in ('pending', 'ordered', 'delivered', 'cancelled'):
        o.status = new_status
        if new_status == 'delivered':
            o.delivered_at = datetime.utcnow()
    if not safe_commit():
        flash(_('Save failed'), 'error')
        return redirect(url_for('equipment.equipment_list'))
    return redirect(url_for('equipment.equipment_list'))
